import type { Coupon } from "./types";

export const NEIGHBORHOODS = [
  "Russafa",
  "El Carme",
  "Ciutat Vella",
  "El Cabanyal",
  "Benimaclet",
  "Extramurs",
  "L'Eixample",
  "Campanar",
  "Patraix",
  "Algirós",
  "El Pla del Real",
];

export const COUPONS: Coupon[] = [
  {
    id: "cafe-horas-2x1",
    title: "2x1 en cafés de especialidad",
    business: "Café de las Horas",
    category: "cafeterias",
    neighborhood: "Ciutat Vella",
    address: "Carrer del Comte d'Almodóvar, 1",
    discountLabel: "2x1",
    discountType: "2x1",
    discountValue: 50,
    estimatedSaving: 3.2,
    description:
      "Disfruta de dos cafés de especialidad al precio de uno en pleno centro histórico. Válido de lunes a viernes hasta las 13h.",
    terms: "No acumulable con otras promociones. Máximo un cupón por mesa.",
    validUntil: "2026-08-31",
    code: "HORAS2X1",
    emoji: "☕",
    rating: 4.6,
    distanceKm: 0.4,
    featured: true,
  },
  {
    id: "ruzafa-brunch-30",
    title: "-30% en brunch de fin de semana",
    business: "Dulce de Leche Boutique",
    category: "cafeterias",
    neighborhood: "Russafa",
    address: "Carrer del Pare Perera, 5",
    discountLabel: "-30%",
    discountType: "porcentaje",
    discountValue: 30,
    estimatedSaving: 7.5,
    description:
      "El mejor brunch de Russafa con un 30% de descuento sábados y domingos. Tostadas, huevos benedictinos y repostería casera.",
    terms: "Solo sábados y domingos. Aforo limitado, recomendable reservar.",
    validUntil: "2026-07-15",
    code: "BRUNCH30",
    emoji: "🥐",
    rating: 4.8,
    distanceKm: 1.1,
    featured: true,
  },
  {
    id: "paella-mediterranea-15",
    title: "Paella valenciana + bebida por 15€",
    business: "Casa Carmela",
    category: "restauracion",
    neighborhood: "El Cabanyal",
    address: "Carrer d'Isabel de Villena, 155",
    discountLabel: "15€",
    discountType: "fijo",
    discountValue: 8,
    estimatedSaving: 8,
    description:
      "Auténtica paella valenciana a leña frente al mar, con bebida incluida por solo 15€ por persona (mínimo 2 personas).",
    terms: "Mínimo 2 comensales. Reserva previa obligatoria. No festivos.",
    validUntil: "2026-09-30",
    code: "PAELLA15",
    emoji: "🥘",
    rating: 4.9,
    distanceKm: 3.2,
    featured: true,
  },
  {
    id: "horchata-fartons-2x1",
    title: "2x1 en horchata con fartons",
    business: "Horchatería Daniel",
    category: "cafeterias",
    neighborhood: "Ciutat Vella",
    address: "Mercat Central, parada 138",
    discountLabel: "2x1",
    discountType: "2x1",
    discountValue: 50,
    estimatedSaving: 4,
    description:
      "La horchata artesanal más famosa del Mercat Central. Llévate dos vasos con fartons al precio de uno.",
    terms: "Para llevar o consumir en barra. Hasta agotar existencias diarias.",
    validUntil: "2026-08-15",
    code: "HORCHATA21",
    emoji: "🥛",
    rating: 4.7,
    distanceKm: 0.6,
  },
  {
    id: "burger-benimaclet-25",
    title: "-25% en hamburguesas gourmet",
    business: "La Burgesa",
    category: "restauracion",
    neighborhood: "Benimaclet",
    address: "Carrer de Baró de San Petrillo, 14",
    discountLabel: "-25%",
    discountType: "porcentaje",
    discountValue: 25,
    estimatedSaving: 4.5,
    description:
      "Hamburguesas 100% artesanas con carne de proximidad. 25% de descuento de domingo a jueves.",
    terms: "No válido viernes ni sábado. Solo consumo en local.",
    validUntil: "2026-06-30",
    code: "BURGER25",
    emoji: "🍔",
    rating: 4.4,
    distanceKm: 2.7,
  },
  {
    id: "moda-carmen-20",
    title: "-20% en toda la tienda",
    business: "Bartleby Concept Store",
    category: "moda",
    neighborhood: "El Carme",
    address: "Carrer dels Cavallers, 36",
    discountLabel: "-20%",
    discountType: "porcentaje",
    discountValue: 20,
    estimatedSaving: 12,
    description:
      "Moda local y de diseñadores valencianos. 20% en toda la colección de temporada presentando este cupón.",
    terms: "No acumulable con rebajas. Un uso por cliente.",
    validUntil: "2026-07-31",
    code: "BARTLEBY20",
    emoji: "🧥",
    rating: 4.5,
    distanceKm: 0.9,
  },
  {
    id: "zapatos-eixample-2x1",
    title: "2ª unidad al 50%",
    business: "Calzados Mediterráneo",
    category: "moda",
    neighborhood: "L'Eixample",
    address: "Carrer de Russafa, 22",
    discountLabel: "2ª -50%",
    discountType: "2x1",
    discountValue: 25,
    estimatedSaving: 25,
    description:
      "Llévate la segunda pareja de zapatos a mitad de precio. Aplica sobre la unidad de menor valor.",
    terms: "Sobre el artículo de menor precio. No acumulable.",
    validUntil: "2026-06-15",
    code: "ZAPATO50",
    emoji: "👟",
    rating: 4.2,
    distanceKm: 1.4,
  },
  {
    id: "peluqueria-russafa-30",
    title: "-30% en corte y peinado",
    business: "Studio Pelo Russafa",
    category: "belleza",
    neighborhood: "Russafa",
    address: "Carrer de Cádiz, 48",
    discountLabel: "-30%",
    discountType: "porcentaje",
    discountValue: 30,
    estimatedSaving: 9,
    description:
      "Renueva tu look con un 30% de descuento en corte + peinado. Profesionales con más de 10 años de experiencia.",
    terms: "Cita previa. Válido de martes a jueves.",
    validUntil: "2026-07-20",
    code: "PELO30",
    emoji: "💇",
    rating: 4.6,
    distanceKm: 1.0,
  },
  {
    id: "spa-pla-real-40",
    title: "Circuito spa -40%",
    business: "Aqua Urban Spa",
    category: "belleza",
    neighborhood: "El Pla del Real",
    address: "Avinguda d'Aragó, 30",
    discountLabel: "-40%",
    discountType: "porcentaje",
    discountValue: 40,
    estimatedSaving: 18,
    description:
      "Circuito termal de 90 minutos con un 40% de descuento entre semana. Sauna, jacuzzi y zona de relax.",
    terms: "De lunes a viernes. Imprescindible reserva. Mayores de 16 años.",
    validUntil: "2026-08-31",
    code: "SPA40",
    emoji: "🧖",
    rating: 4.8,
    distanceKm: 2.1,
    featured: true,
  },
  {
    id: "cine-babel-3eur",
    title: "Entrada de cine por 3€",
    business: "Cines Babel",
    category: "ocio",
    neighborhood: "L'Eixample",
    address: "Carrer de Vicent Sancho Tello, 10",
    discountLabel: "3€",
    discountType: "fijo",
    discountValue: 5,
    estimatedSaving: 5,
    description:
      "Versión original subtitulada por solo 3€ los miércoles. El cine de autor de referencia en Valencia.",
    terms: "Solo miércoles no festivos. Sujeto a disponibilidad de sala.",
    validUntil: "2026-12-31",
    code: "BABEL3",
    emoji: "🎬",
    rating: 4.7,
    distanceKm: 1.8,
  },
  {
    id: "escape-carmen-25",
    title: "-25% en escape room",
    business: "Enigma Valencia",
    category: "ocio",
    neighborhood: "El Carme",
    address: "Carrer Baix, 12",
    discountLabel: "-25%",
    discountType: "porcentaje",
    discountValue: 25,
    estimatedSaving: 15,
    description:
      "Vive una aventura de 60 minutos con un 25% de descuento para grupos de 3 a 6 personas.",
    terms: "Reserva online. No válido sábados por la tarde.",
    validUntil: "2026-07-10",
    code: "ENIGMA25",
    emoji: "🗝️",
    rating: 4.9,
    distanceKm: 0.8,
  },
  {
    id: "super-patraix-10",
    title: "10€ de descuento en compra +50€",
    business: "Frutas y Verduras El Huerto",
    category: "supermercado",
    neighborhood: "Patraix",
    address: "Carrer de l'Arquitecte Tolsà, 7",
    discountLabel: "-10€",
    discountType: "fijo",
    discountValue: 10,
    estimatedSaving: 10,
    description:
      "Producto fresco de la huerta valenciana. 10€ de descuento en compras superiores a 50€.",
    terms: "Compra mínima 50€. Un cupón por cliente y semana.",
    validUntil: "2026-06-30",
    code: "HUERTO10",
    emoji: "🥬",
    rating: 4.5,
    distanceKm: 3.5,
  },
  {
    id: "vino-extramurs-15",
    title: "-15% en vinos D.O. Valencia",
    business: "Vinoteca La Cata",
    category: "supermercado",
    neighborhood: "Extramurs",
    address: "Carrer de Calixt III, 19",
    discountLabel: "-15%",
    discountType: "porcentaje",
    discountValue: 15,
    estimatedSaving: 6,
    description:
      "Selección de vinos con Denominación de Origen Valencia con un 15% de descuento. Asesoramiento incluido.",
    terms: "No aplicable a botellas ya rebajadas. Mayores de 18 años.",
    validUntil: "2026-09-15",
    code: "CATA15",
    emoji: "🍷",
    rating: 4.6,
    distanceKm: 1.9,
  },
  {
    id: "gym-algiros-1mes",
    title: "1 mes gratis al matricularte",
    business: "Fit Algirós",
    category: "deporte",
    neighborhood: "Algirós",
    address: "Avinguda de Blasco Ibáñez, 142",
    discountLabel: "1 mes gratis",
    discountType: "regalo",
    discountValue: 35,
    estimatedSaving: 35,
    description:
      "Matricúlate en cualquier plan anual y consigue el primer mes totalmente gratis. Clases dirigidas incluidas.",
    terms: "Solo nuevas altas con permanencia de 6 meses. No reembolsable.",
    validUntil: "2026-07-31",
    code: "FITGRATIS",
    emoji: "🏋️",
    rating: 4.3,
    distanceKm: 2.4,
  },
  {
    id: "yoga-benimaclet-2x1",
    title: "2x1 en clase de prueba",
    business: "Espai Ioga Benimaclet",
    category: "deporte",
    neighborhood: "Benimaclet",
    address: "Carrer de Guardia Civil, 3",
    discountLabel: "2x1",
    discountType: "2x1",
    discountValue: 50,
    estimatedSaving: 12,
    description:
      "Ven con quien quieras: dos clases de prueba de yoga o pilates al precio de una.",
    terms: "Solo primera visita. Imprescindible reservar plaza.",
    validUntil: "2026-08-20",
    code: "IOGA2X1",
    emoji: "🧘",
    rating: 4.8,
    distanceKm: 2.9,
  },
  {
    id: "optica-campanar-50",
    title: "2ª gafa graduada -50%",
    business: "Òptica Campanar",
    category: "salud",
    neighborhood: "Campanar",
    address: "Carrer del Doctor Vicente Zaragozá, 21",
    discountLabel: "2ª -50%",
    discountType: "porcentaje",
    discountValue: 50,
    estimatedSaving: 60,
    description:
      "Llévate tu segunda gafa graduada con un 50% de descuento. Incluye revisión visual gratuita.",
    terms: "Sobre la montura de menor importe. No acumulable a seguros.",
    validUntil: "2026-10-31",
    code: "OPTICA50",
    emoji: "👓",
    rating: 4.5,
    distanceKm: 4.1,
  },
  {
    id: "farmacia-quatre-20",
    title: "-20% en dermocosmética",
    business: "Farmacia Plaça",
    category: "salud",
    neighborhood: "Extramurs",
    address: "Plaça d'Espanya, 4",
    discountLabel: "-20%",
    discountType: "porcentaje",
    discountValue: 20,
    estimatedSaving: 8,
    description:
      "20% de descuento en toda la gama de dermocosmética y protección solar. Asesoramiento farmacéutico.",
    terms: "No aplicable a medicamentos. Hasta fin de existencias.",
    validUntil: "2026-07-05",
    code: "DERMO20",
    emoji: "🧴",
    rating: 4.4,
    distanceKm: 2.0,
  },
  {
    id: "ferreteria-patraix-15",
    title: "-15% en menaje y decoración",
    business: "Casa & Hogar Patraix",
    category: "hogar",
    neighborhood: "Patraix",
    address: "Carrer de Salabert, 33",
    discountLabel: "-15%",
    discountType: "porcentaje",
    discountValue: 15,
    estimatedSaving: 9,
    description:
      "Renueva tu hogar con un 15% de descuento en menaje, textil y decoración.",
    terms: "No acumulable con liquidaciones. Un uso por cliente.",
    validUntil: "2026-08-10",
    code: "HOGAR15",
    emoji: "🛋️",
    rating: 4.2,
    distanceKm: 3.6,
  },
  {
    id: "plantas-cabanyal-25",
    title: "-25% en plantas de interior",
    business: "Vivers del Cabanyal",
    category: "hogar",
    neighborhood: "El Cabanyal",
    address: "Carrer de la Reina, 84",
    discountLabel: "-25%",
    discountType: "porcentaje",
    discountValue: 25,
    estimatedSaving: 7,
    description:
      "Llena tu casa de verde con un 25% de descuento en toda la selección de plantas de interior.",
    terms: "No incluye macetas de diseño. Hasta agotar stock.",
    validUntil: "2026-06-25",
    code: "VERDE25",
    emoji: "🪴",
    rating: 4.7,
    distanceKm: 3.0,
  },
  {
    id: "movil-eixample-30",
    title: "-30% en reparación de móvil",
    business: "TecnoFix Valencia",
    category: "tecnologia",
    neighborhood: "L'Eixample",
    address: "Gran Via del Marqués del Túria, 51",
    discountLabel: "-30%",
    discountType: "porcentaje",
    discountValue: 30,
    estimatedSaving: 18,
    description:
      "Reparación de pantallas y baterías con un 30% de descuento. Garantía de 6 meses.",
    terms: "No acumulable. Presupuesto sin compromiso.",
    validUntil: "2026-09-01",
    code: "TECNO30",
    emoji: "📱",
    rating: 4.6,
    distanceKm: 1.5,
  },
  {
    id: "tapas-carmen-12",
    title: "Ruta de 3 tapas + caña por 12€",
    business: "Tasca El Cantó",
    category: "restauracion",
    neighborhood: "El Carme",
    address: "Carrer de Roters, 9",
    discountLabel: "12€",
    discountType: "fijo",
    discountValue: 6,
    estimatedSaving: 6,
    description:
      "Tres tapas de autor y una caña por solo 12€. Cocina valenciana de toda la vida con un toque moderno.",
    terms: "Por persona. No válido en festivos ni vísperas.",
    validUntil: "2026-07-31",
    code: "TAPAS12",
    emoji: "🍤",
    rating: 4.5,
    distanceKm: 0.7,
  },
  {
    id: "heladeria-russafa-2x1",
    title: "2x1 en helados artesanos",
    business: "Gelat Russafa",
    category: "cafeterias",
    neighborhood: "Russafa",
    address: "Carrer de Sueca, 61",
    discountLabel: "2x1",
    discountType: "2x1",
    discountValue: 50,
    estimatedSaving: 3.5,
    description:
      "Helado artesano elaborado a diario. Dos tarrinas al precio de una de lunes a jueves.",
    terms: "De lunes a jueves. Tarrinas del mismo o menor tamaño.",
    validUntil: "2026-09-30",
    code: "GELAT21",
    emoji: "🍦",
    rating: 4.7,
    distanceKm: 1.2,
  },
  {
    id: "libreria-pla-real-10",
    title: "-10% en libros + café gratis",
    business: "Llibreria Ramon Llull",
    category: "ocio",
    neighborhood: "El Pla del Real",
    address: "Carrer del Comte d'Altea, 29",
    discountLabel: "-10%",
    discountType: "porcentaje",
    discountValue: 10,
    estimatedSaving: 4,
    description:
      "10% de descuento en toda la librería y un café de regalo para que disfrutes de tu nueva lectura.",
    terms: "No aplicable a libros de texto. Un café por compra.",
    validUntil: "2026-08-31",
    code: "LLULL10",
    emoji: "📚",
    rating: 4.8,
    distanceKm: 2.2,
  },
  {
    id: "barberia-cabanyal-20",
    title: "-20% en corte + barba",
    business: "Barbería del Mar",
    category: "belleza",
    neighborhood: "El Cabanyal",
    address: "Carrer de Josep Benlliure, 120",
    discountLabel: "-20%",
    discountType: "porcentaje",
    discountValue: 20,
    estimatedSaving: 5,
    description:
      "Corte de pelo y arreglo de barba con un 20% de descuento. Ambiente clásico junto a la playa.",
    terms: "Cita previa recomendada. De martes a sábado.",
    validUntil: "2026-07-15",
    code: "BARBA20",
    emoji: "💈",
    rating: 4.6,
    distanceKm: 3.1,
  },
  {
    id: "deporte-campanar-30",
    title: "-30% en ropa deportiva",
    business: "Sport Outlet Campanar",
    category: "deporte",
    neighborhood: "Campanar",
    address: "Avinguda del General Avilés, 36",
    discountLabel: "-30%",
    discountType: "porcentaje",
    discountValue: 30,
    estimatedSaving: 21,
    description:
      "30% de descuento en ropa y calzado deportivo de primeras marcas. Outlet permanente.",
    terms: "No acumulable a otras ofertas del outlet.",
    validUntil: "2026-06-20",
    code: "SPORT30",
    emoji: "👟",
    rating: 4.3,
    distanceKm: 4.0,
  },
  {
    id: "veterinario-algiros-revision",
    title: "Revisión veterinaria gratuita",
    business: "Clínica Veterinària Algirós",
    category: "salud",
    neighborhood: "Algirós",
    address: "Carrer del Serpis, 27",
    discountLabel: "Gratis",
    discountType: "regalo",
    discountValue: 25,
    estimatedSaving: 25,
    description:
      "Primera revisión veterinaria completa sin coste para tu mascota. Incluye chequeo general.",
    terms: "Solo primera visita. No incluye pruebas ni tratamientos.",
    validUntil: "2026-08-31",
    code: "VETGRATIS",
    emoji: "🐾",
    rating: 4.9,
    distanceKm: 2.6,
  },
  {
    id: "floristeria-eixample-2x1",
    title: "2x1 en ramos de temporada",
    business: "Flors Mercat de Colón",
    category: "hogar",
    neighborhood: "L'Eixample",
    address: "Mercat de Colón, local 12",
    discountLabel: "2x1",
    discountType: "2x1",
    discountValue: 50,
    estimatedSaving: 15,
    description:
      "Dos ramos de flores de temporada al precio de uno. Ideal para regalar o decorar.",
    terms: "Ramos del mismo importe. Sujeto a disponibilidad floral.",
    validUntil: "2026-06-30",
    code: "FLORS21",
    emoji: "💐",
    rating: 4.7,
    distanceKm: 1.6,
  },
  {
    id: "informatica-benimaclet-15",
    title: "-15% en accesorios y portátiles",
    business: "PC Benimaclet",
    category: "tecnologia",
    neighborhood: "Benimaclet",
    address: "Carrer d'Arquitecte Arnau, 18",
    discountLabel: "-15%",
    discountType: "porcentaje",
    discountValue: 15,
    estimatedSaving: 45,
    description:
      "15% de descuento en portátiles, periféricos y accesorios. Montaje de equipos a medida.",
    terms: "No acumulable. No aplicable a componentes en oferta.",
    validUntil: "2026-09-30",
    code: "PCBENI15",
    emoji: "💻",
    rating: 4.4,
    distanceKm: 2.8,
  },
];
